### ISSUE TITLE
Instructions in readme produce a website with broken formatting

### ISSUE THREAD

**Issue by LilithHafner** [LuxDL/DocumenterVitepress.jl#29]
The readme instructions are appealingly minimal. I tried them out on [this PR](https://github.com/LilithHafner/Chairmarks.jl/pull/10) to Chairmarks.jl, but found the result to have broken formatting. Ideally (and aspirationally), those incredibly simple instructions would produce a website of a similar quality as https://luxdl.github.io/DocumenterVitepress.jl/dev/. In the interim, it would be appropriate to only provide instructions that are complete enough to produce a website with functional formatting.

**Comment by asinghvi17** [comment]
#28 should fix that significantly.

**Comment by asinghvi17** [comment]
That being said, because the navbar and sidebar are determined in `config.mts`, we should probably come to a decision as to whether to hook those into Documenter or tell users to do it themselves, basically

**Comment by asinghvi17** [comment]
I just updated a bunch of stuff including the README - how does it look now @LilithHafner?

**Comment by LilithHafner** [comment]
Sorry about the delay. I tried again and it is unfortunately, still not working for me (https://github.com/LilithHafner/Chairmarks.jl/pull/35)

- In addition to the readme instructions I need to add a package.json file for docs to build
- Even after doing this they are not formatted.
